Catch and log exceptions when enabling tracing.
Due to an android gradle bug calls to forceEnableAppTracing() may
fail with NoSuchMethodError at runtime.
Instead of crashing, just catch and log this exception.